[build]
  command = "npm run build"
  publish = ".next"   # leave empty, plugin sets it automatically

[[plugins]]
  package = "@netlify/plugin-nextjs"
  inputs = { appPath = "src/app" }


[build.environment]
  NODE_VERSION = "20"
